apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
  labels:
    app: currency-converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: devanshpandey21/flask-currency-converter:latest
        ports:
        - containerPort: 5000
